services:
  silent-disco:
    build: .
    container_name: silent-disco
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - SPOTIFY_REDIRECT_URI=https://silentdisco.evilo.eu/callback
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-change_me}
      - SECRET_KEY=${SECRET_KEY:-change_me}
      - SPOTIFY_CACHE_DIR=/app/caches
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./caches:/app/caches
